/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'
import type { SceneConfig } from '#validators/scene'

export class MatrixSchema extends BaseModel {
  static $columns = [
    'config',
    'createdAt',
    'height',
    'id',
    'name',
    'updatedAt',
    'userId',
    'width',
  ] as const
  $columns = MatrixSchema.$columns
  @column()
  declare config: any
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare height: number
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
  @column()
  declare width: number
}

export class RendererSchema extends BaseModel {
  static $columns = [
    'capabilities',
    'createdAt',
    'endpoint',
    'id',
    'isDefault',
    'lastSeenAt',
    'name',
    'ownerId',
    'status',
    'tokenHash',
    'tokenPrefix',
    'updatedAt',
    'version',
  ] as const
  $columns = RendererSchema.$columns
  @column()
  declare capabilities: any | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare endpoint: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isDefault: boolean
  @column.dateTime()
  declare lastSeenAt: DateTime | null
  @column()
  declare name: string
  @column()
  declare ownerId: string | null
  @column()
  declare status: 'online' | 'offline'
  @column({ serializeAs: null })
  declare tokenHash: string
  @column()
  declare tokenPrefix: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare version: string | null
}

export class SceneSchema extends BaseModel {
  static $columns = [
    'config',
    'createdAt',
    'height',
    'id',
    'name',
    'targetFps',
    'updatedAt',
    'userId',
    'version',
    'width',
  ] as const
  $columns = SceneSchema.$columns
  @column()
  declare config: SceneConfig
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare height: number
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare targetFps: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
  @column()
  declare version: number
  @column()
  declare width: number
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: string
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
