/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'
import type { RendererEndpoints } from '#validators/renderer'
import type { SceneConfig } from '#validators/scene'

export class DeviceSchema extends BaseModel {
  static $columns = [
    'brightness',
    'chainLength',
    'createdAt',
    'firmwareVersion',
    'height',
    'id',
    'ipAddress',
    'kind',
    'lastSeenAt',
    'maxFps',
    'name',
    'offlineGrace',
    'panelType',
    'protocolVersion',
    'rendererId',
    'sceneId',
    'status',
    'tokenHash',
    'tokenPrefix',
    'updatedAt',
    'userId',
    'width',
  ] as const
  $columns = DeviceSchema.$columns
  @column()
  declare brightness: number
  @column()
  declare chainLength: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare firmwareVersion: string | null
  @column()
  declare height: number
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare ipAddress: string | null
  @column()
  declare kind: 'hardware' | 'simulator'
  @column.dateTime()
  declare lastSeenAt: DateTime | null
  @column()
  declare maxFps: number | null
  @column()
  declare name: string
  @column()
  declare offlineGrace: number | null
  @column()
  declare panelType: 'hub75'
  @column()
  declare protocolVersion: number | null
  @column()
  declare rendererId: string
  @column()
  declare sceneId: string | null
  @column()
  declare status: 'online' | 'offline' | 'error'
  @column({ serializeAs: null })
  declare tokenHash: string
  @column()
  declare tokenPrefix: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
  @column()
  declare width: number
}

export class RendererSchema extends BaseModel {
  static $columns = [
    'capabilities',
    'createdAt',
    'endpoints',
    'id',
    'isDefault',
    'lastSeenAt',
    'name',
    'ownerId',
    'status',
    'tokenHash',
    'tokenPrefix',
    'updatedAt',
    'version',
  ] as const
  $columns = RendererSchema.$columns
  @column()
  declare capabilities: any | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare endpoints: RendererEndpoints | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isDefault: boolean
  @column.dateTime()
  declare lastSeenAt: DateTime | null
  @column()
  declare name: string
  @column()
  declare ownerId: string | null
  @column()
  declare status: 'online' | 'offline'
  @column({ serializeAs: null })
  declare tokenHash: string
  @column()
  declare tokenPrefix: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare version: string | null
}

export class SceneSchema extends BaseModel {
  static $columns = [
    'config',
    'createdAt',
    'height',
    'id',
    'name',
    'targetFps',
    'updatedAt',
    'userId',
    'version',
    'width',
  ] as const
  $columns = SceneSchema.$columns
  @column()
  declare config: SceneConfig
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare height: number
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare targetFps: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
  @column()
  declare version: number
  @column()
  declare width: number
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: string
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
