/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Devices: () => import('#controllers/devices_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Renderers: () => import('#controllers/renderers_controller'),
  Scenes: () => import('#controllers/scenes_controller'),
  Session: () => import('#controllers/session_controller'),
}
