/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

import BaseDeviceEvent from '#events/base/device_event'
import BaseDomainEvent from '#events/base/domain_event'
import BaseRendererEvent from '#events/base/renderer_event'
import BaseSceneEvent from '#events/base/scene_event'
import DeviceCreated from '#events/device_created'
import DeviceDeleted from '#events/device_deleted'
import DeviceUpdated from '#events/device_updated'
import RendererCreated from '#events/renderer_created'
import RendererDeleted from '#events/renderer_deleted'
import RendererUpdated from '#events/renderer_updated'
import SceneCreated from '#events/scene_created'
import SceneDeleted from '#events/scene_deleted'
import SceneUpdated from '#events/scene_updated'

export const events = {
  base: {
    DeviceEvent: BaseDeviceEvent,
    DomainEvent: BaseDomainEvent,
    RendererEvent: BaseRendererEvent,
    SceneEvent: BaseSceneEvent,
  },
  DeviceCreated: DeviceCreated,
  DeviceDeleted: DeviceDeleted,
  DeviceUpdated: DeviceUpdated,
  RendererCreated: RendererCreated,
  RendererDeleted: RendererDeleted,
  RendererUpdated: RendererUpdated,
  SceneCreated: SceneCreated,
  SceneDeleted: SceneDeleted,
  SceneUpdated: SceneUpdated,
}
