/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

import BaseDomainEvent from '#events/base/domain_event'
import BaseMatrixEvent from '#events/base/matrix_event'
import BaseRendererEvent from '#events/base/renderer_event'
import BaseSceneEvent from '#events/base/scene_event'
import MatrixCreated from '#events/matrix_created'
import MatrixDeleted from '#events/matrix_deleted'
import MatrixUpdated from '#events/matrix_updated'
import RendererCreated from '#events/renderer_created'
import RendererDeleted from '#events/renderer_deleted'
import RendererUpdated from '#events/renderer_updated'
import SceneCreated from '#events/scene_created'
import SceneDeleted from '#events/scene_deleted'
import SceneUpdated from '#events/scene_updated'

export const events = {
  base: {
    DomainEvent: BaseDomainEvent,
    MatrixEvent: BaseMatrixEvent,
    RendererEvent: BaseRendererEvent,
    SceneEvent: BaseSceneEvent,
  },
  MatrixCreated: MatrixCreated,
  MatrixDeleted: MatrixDeleted,
  MatrixUpdated: MatrixUpdated,
  RendererCreated: RendererCreated,
  RendererDeleted: RendererDeleted,
  RendererUpdated: RendererUpdated,
  SceneCreated: SceneCreated,
  SceneDeleted: SceneDeleted,
  SceneUpdated: SceneUpdated,
}
