/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type DeviceTransformer from '#transformers/device_transformer'
import type DeviceWithTokenTransformer from '#transformers/device_with_token_transformer'
import type RendererTransformer from '#transformers/renderer_transformer'
import type RendererWithTokenTransformer from '#transformers/renderer_with_token_transformer'
import type SceneTransformer from '#transformers/scene_transformer'
import type UserTransformer from '#transformers/user_transformer'

export namespace Data {
  export type Device = InferData<DeviceTransformer>
  export namespace Device {
    export type Variants = InferVariants<DeviceTransformer>
  }
  export type DeviceWithToken = InferData<DeviceWithTokenTransformer>
  export namespace DeviceWithToken {
    export type Variants = InferVariants<DeviceWithTokenTransformer>
  }
  export type Renderer = InferData<RendererTransformer>
  export namespace Renderer {
    export type Variants = InferVariants<RendererTransformer>
  }
  export type RendererWithToken = InferData<RendererWithTokenTransformer>
  export namespace RendererWithToken {
    export type Variants = InferVariants<RendererWithTokenTransformer>
  }
  export type Scene = InferData<SceneTransformer>
  export namespace Scene {
    export type Variants = InferVariants<SceneTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
}
